//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthleteTable
    {
        public int AthleteMatchID { get; set; }
        public string AthleteName { get; set; }
        public int SNO { get; set; }
        public int ClassID { get; set; }
        public string Gender { get; set; }
        public int MatchID { get; set; }
        public Nullable<double> Grade { get; set; }
        public string PrizeID { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual MatchTable MatchTable { get; set; }
        public virtual RegistrationTable RegistrationTable { get; set; }
    }
}
