//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassTable()
        {
            this.AthleteTable = new HashSet<AthleteTable>();
            this.RegistrationTable = new HashSet<RegistrationTable>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public int ClassSize { get; set; }
        public Nullable<int> ClassScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AthleteTable> AthleteTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationTable> RegistrationTable { get; set; }
    }
}
