//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchTable()
        {
            this.AthleteTable = new HashSet<AthleteTable>();
            this.PrizeTable = new HashSet<PrizeTable>();
            this.RefereeTable = new HashSet<RefereeTable>();
            this.ScoreTable = new HashSet<ScoreTable>();
        }
    
        public int MatchID { get; set; }
        public string MatchName { get; set; }
        public string Gender { get; set; }
        public int LocationID { get; set; }
        public string MatchType { get; set; }
        public string MatchRule { get; set; }
        public int Max { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AthleteTable> AthleteTable { get; set; }
        public virtual LocationTable LocationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrizeTable> PrizeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefereeTable> RefereeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreTable> ScoreTable { get; set; }
    }
}
