//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsDBEntities : DbContext
    {
        public SportsDBEntities()
            : base("name=SportsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AthleteTable> AthleteTable { get; set; }
        public virtual DbSet<ClassTable> ClassTable { get; set; }
        public virtual DbSet<LocationTable> LocationTable { get; set; }
        public virtual DbSet<MatchTable> MatchTable { get; set; }
        public virtual DbSet<PrizeTable> PrizeTable { get; set; }
        public virtual DbSet<RefereeTable> RefereeTable { get; set; }
        public virtual DbSet<RegistrationTable> RegistrationTable { get; set; }
        public virtual DbSet<ScoreTable> ScoreTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
